-- ============================================================
-- FabHub Migration 045 — billing-schedule idempotency flag
-- Run in Supabase SQL Editor (safe to run multiple times)
--
-- Root cause of duplicate billing milestones: the schedule was generated by
-- three separate client code paths, each guarded only by in-memory state, so a
-- generation firing before the billings store hydrated (cold load, remount, or a
-- second device) produced a full duplicate set. This adds a PERSISTENT per-deal
-- flag that the (now single) generator checks and sets, so a deal's schedule can
-- never be auto-generated twice.
--   deals.billing_generated — true once a billing schedule has been generated.
-- ============================================================

alter table deals add column if not exists billing_generated boolean not null default false;

-- Backfill: any deal that already has a milestone has been generated.
update deals d
set billing_generated = true
where d.billing_generated = false
  and exists (select 1 from billing_milestones m where m.deal_id = d.id);

select 'Migration 045 applied — deals.billing_generated added + backfilled' as status;
